#!/usr/bin/env python3
"""Create the StarRocks views measurements.device_series and series_values.

device_series: one row per device and measurement series, refreshed by
StarRocks every 10 minutes. Dashboards use it for "pick a device, then its
series": answering "which device has data in which of the per-fragment tables"
any other way means scanning every table in polaris.cdc_measurement.

series_values: a plain view with all series in one long table (time, source,
metric, value, unit), so a dashboard can chart several series at once with
`WHERE metric IN (...)`. Each UNION ALL branch carries its metric as a
constant, so StarRocks prunes every branch that isn't selected and only scans
the tables of the chosen series.

Every Cumulocity measurement fragment is its own Iceberg table there, with one
struct column per series (`<series>`.`value`, optionally `.unit`). The view's
SQL is generated from that layout, so re-run this script when new measurement
types or series appear (new devices and values are picked up by the refresh).

Usage (from starrocks/):  python3 init/device_series.py
STARROCKS_CONTAINER defaults to "starrocks".
"""
import os
import re
import subprocess
import sys

SCHEMA = "cdc_measurement"
INVENTORY = "polaris.latest_inventory.inventory"
LOOKUP = "measurements.device_series"
VALUES = "measurements.series_values"
BASE_COLUMNS = {"id", "source", "eventType", "time", "type"}
SEP = " · "  # device label = "<name> · <id>"; names are not unique


class StarRocks:
    """SQL through the mysql client inside the StarRocks container.

    The FE HTTP SQL API only accepts SELECT/SHOW, and the view needs DDL.
    """

    def __init__(self, container: str = None):
        container = container or os.environ.get("STARROCKS_CONTAINER", "starrocks")
        self.cmd = ["docker", "exec", "-i", container,
                    "mysql", "-h127.0.0.1", "-P9030", "-uroot", "--batch", "--skip-column-names"]

    def sql(self, query: str) -> list:
        res = subprocess.run(self.cmd, input=query.strip().rstrip(";") + ";",
                             capture_output=True, text=True)
        if res.returncode:
            sys.exit(f"StarRocks: {res.stderr.strip()}\n{query}")
        return [line.split("\t") for line in res.stdout.splitlines()]


def ident(name: str) -> str:
    return "`" + name.replace("`", "``") + "`"


def literal(text: str) -> str:
    return "'" + text.replace("\\", "\\\\").replace("'", "''") + "'"


def pretty(name: str) -> str:
    # Cumulocity XML-escapes special characters in fragment names: _x0020 -> " "
    return re.sub(r"_x([0-9A-Fa-f]{4})_?", lambda m: chr(int(m.group(1), 16)), name)


def discover(sr: StarRocks) -> list:
    """[(table, struct column, has_unit, metric label)] for every measurement series."""
    rows = sr.sql(f"""
        SELECT TABLE_NAME, COLUMN_NAME, COLUMN_TYPE
        FROM polaris.information_schema.columns
        WHERE TABLE_SCHEMA = '{SCHEMA}'
        ORDER BY TABLE_NAME, ORDINAL_POSITION""")
    series = []
    for table, column, ctype in rows:
        ctype = ctype.lower()
        if column not in BASE_COLUMNS and ctype.startswith("struct<") and "`value`" in ctype:
            series.append((table, column, "`unit`" in ctype, f"{table}.{pretty(column)}"))
    if not series:
        sys.exit(f"no measurement series found in polaris.{SCHEMA}")
    return series


def view_sql(series) -> str:
    branches = []
    for table, column, has_unit, metric in series:
        unit = f"MAX({ident(column)}.`unit`)" if has_unit else "CAST(NULL AS VARCHAR)"
        branches.append(
            f"  SELECT source, {literal(table)} AS fragment, {literal(column)} AS series_column,\n"
            f"         {literal(pretty(column))} AS series, {literal(metric)} AS metric, {unit} AS unit,\n"
            f"         COUNT(*) AS measurements, MIN(time) AS first_time, MAX(time) AS last_time\n"
            f"  FROM polaris.{SCHEMA}.{ident(table)}\n"
            f"  WHERE eventType = 'MEASUREMENT_CREATE' AND {ident(column)}.`value` IS NOT NULL\n"
            f"  GROUP BY source")
    return (
        f"CREATE MATERIALIZED VIEW {LOOKUP}\n"
        f"COMMENT 'Device/series lookup for dashboards (generated by init/device_series.py)'\n"
        f"REFRESH ASYNC EVERY (INTERVAL 10 MINUTE)\n"
        f"PROPERTIES (\"replication_num\" = \"1\")\n"
        f"AS SELECT s.source AS device_id,\n"
        f"       CASE WHEN i.name IS NULL THEN s.source ELSE CONCAT(i.name, '{SEP}', s.source) END AS device,\n"
        f"       s.fragment, s.series_column, s.series, s.metric, s.unit,\n"
        f"       s.measurements, s.first_time, s.last_time\n"
        f"FROM (\n" + "\n  UNION ALL\n".join(branches) + "\n) s\n"
        f"LEFT JOIN {INVENTORY} i ON i.id = s.source")


def values_sql(series) -> str:
    branches = []
    for table, column, has_unit, metric in series:
        unit = f"{ident(column)}.`unit`" if has_unit else "CAST(NULL AS VARCHAR)"
        branches.append(
            f"SELECT time, source, {literal(metric)} AS metric,\n"
            f"       CAST({ident(column)}.`value` AS DOUBLE) AS value, {unit} AS unit\n"
            f"FROM polaris.{SCHEMA}.{ident(table)}\n"
            f"WHERE eventType = 'MEASUREMENT_CREATE' AND {ident(column)}.`value` IS NOT NULL")
    return (f"CREATE OR REPLACE VIEW {VALUES}\n"
            f"COMMENT 'All measurement series, long format (generated by init/device_series.py)'\n"
            f"AS\n" + "\nUNION ALL\n".join(branches))


def create(sr: StarRocks = None) -> list:
    """(Re)create both views and fill the lookup; returns the discovered series."""
    sr = sr or StarRocks()
    series = discover(sr)
    sr.sql(f"CREATE DATABASE IF NOT EXISTS {LOOKUP.split('.')[0]}")
    sr.sql(f"DROP MATERIALIZED VIEW IF EXISTS {LOOKUP}")
    sr.sql(view_sql(series))
    sr.sql(f"REFRESH MATERIALIZED VIEW {LOOKUP} WITH SYNC MODE")
    sr.sql(values_sql(series))
    return series


if __name__ == "__main__":
    sr = StarRocks()
    series = create(sr)
    pairs, devices = sr.sql(f"SELECT COUNT(*), COUNT(DISTINCT device_id) FROM {LOOKUP}")[0]
    print(f"{LOOKUP}: {len({s[0] for s in series})} tables, {len(series)} series, "
          f"{pairs} device/series pairs, {devices} devices; {VALUES} recreated")
