#!/usr/bin/env python3
"""Create or refresh the "Measurements" dashboard in Metabase.

Pick a device, then one of that device's series, and the dashboard shows it.

* Every Cumulocity measurement fragment is its own Iceberg table in
  polaris.cdc_measurement, with one struct column per series (`<series>`.`value`,
  optionally `.unit`). The script reads that layout from information_schema.
* A StarRocks materialized view `measurements.device_series` (one row per device
  and series, refreshed every 10 minutes) feeds the Device and Series filters.
  Metabase can only limit one filter's choices by another for real table
  columns, which is why this small lookup table exists.
* The chart cards are native SQL: a UNION ALL over all series where every branch
  is guarded by a constant `{{series}} = '<fragment>.<series>'`. StarRocks prunes
  the non-matching branches at plan time, so only the selected table is read.

Re-run it whenever new measurement types or series appear; it recreates the
lookup view and updates the cards and dashboard in place (matched by name).

Usage (from starrocks/):  python3 metabase/measurements_dashboard.py
Reads MB_ADMIN_EMAIL / MB_ADMIN_PASSWORD from .env. METABASE_URL defaults to
http://localhost:3000, STARROCKS_CONTAINER to starrocks.
"""
import json
import os
import re
import sys
import time
import urllib.error
import urllib.request
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "init"))
from device_series import SEP, StarRocks, ident, literal  # noqa: E402
import device_series  # noqa: E402

POLARIS_DB_NAME = "StarRocks (Polaris)"
LOOKUP_DB_NAME = "StarRocks (measurements)"
LOOKUP_DB = "measurements"
LOOKUP_TABLE = "device_series"
DASHBOARD_NAME = "Measurements"
COLLECTION_NAME = "Measurements"

T_TIME, T_TEXT, T_NUM = "type/DateTime", "type/Text", "type/Float"


def load_env(path: Path) -> None:
    for line in path.read_text().splitlines():
        m = re.match(r"^([A-Z_][A-Z0-9_]*)=(.*)$", line)
        if m:
            os.environ.setdefault(m.group(1), m.group(2))


def http(method, url, body=None, headers=None, raw=False):
    data = None if body is None else json.dumps(body).encode()
    req = urllib.request.Request(url, data=data, headers=headers or {}, method=method)
    try:
        with urllib.request.urlopen(req, timeout=600) as resp:
            out = resp.read()
            return out if raw else (json.loads(out) if out else None)
    except urllib.error.HTTPError as e:
        sys.exit(f"{method} {url} failed: {e.code} {e.read().decode()[:800]}")


class Metabase:
    def __init__(self, url: str, email: str, password: str):
        self.url = url.rstrip("/") + "/api"
        self.session = None
        self.session = self.call("POST", "/session", {"username": email, "password": password})["id"]

    def call(self, method, path, body=None):
        headers = {"Content-Type": "application/json"}
        if self.session:
            headers["X-Metabase-Session"] = self.session
        return http(method, self.url + path, body, headers)


def series_sql(series, select_branch) -> str:
    """UNION ALL over all series; Metabase fills {{series}}, {{device}}, {{days}}.

    `1 = 0 [[OR {{series}} = '<metric>']]` is a constant per branch, so StarRocks
    drops every branch except the selected one (and all of them when no series
    is picked) before reading any table.
    """
    branches = []
    for table, column, has_unit, metric in series:
        unit = f"{ident(column)}.`unit`" if has_unit else "CAST(NULL AS VARCHAR)"
        branches.append(
            f"  SELECT time, source, CAST({ident(column)}.`value` AS DOUBLE) AS value, {unit} AS unit\n"
            f"  FROM polaris.{device_series.SCHEMA}.{ident(table)}\n"
            f"  WHERE (1 = 0 [[OR {{{{series}}}} = {literal(metric)}]])\n"
            f"    AND eventType = 'MEASUREMENT_CREATE'\n"
            f"    [[AND source = SUBSTRING_INDEX({{{{device}}}}, '{SEP}', -1)]]\n"
            f"    [[AND time >= DATE_SUB(NOW(), INTERVAL {{{{days}}}} DAY)]]")
    return (
        "-- Generated by starrocks/metabase/measurements_dashboard.py - re-run it instead of editing.\n"
        "WITH m AS (\n" + "\n  UNION ALL\n".join(branches) + "\n),\n"
        f"d AS (SELECT DISTINCT device_id, device FROM {LOOKUP_DB}.{LOOKUP_TABLE})\n"
        + select_branch)


def template_tags():
    return {
        "series": {"id": "t-series", "name": "series", "display-name": "Series", "type": "text"},
        "device": {"id": "t-device", "name": "device", "display-name": "Device", "type": "text"},
        "days": {"id": "t-days", "name": "days", "display-name": "Last days", "type": "number",
                 "default": "7"},
    }


def ensure_metabase_db(mb: Metabase) -> int:
    dbs = {d["name"]: d for d in mb.call("GET", "/database")["data"]}
    details = {"host": "starrocks", "port": 9030, "catalog": "default_catalog", "dbname": LOOKUP_DB,
               "user": "root", "password": "", "let-user-control-scheduling": True}
    # Field values (the filter dropdowns) are rescanned hourly; linked choices are queried live.
    schedules = {"cache_field_values": {"schedule_type": "hourly", "schedule_minute": 15},
                 "metadata_sync": {"schedule_type": "hourly", "schedule_minute": 10}}
    if LOOKUP_DB_NAME in dbs:
        db_id = dbs[LOOKUP_DB_NAME]["id"]
        mb.call("PUT", f"/database/{db_id}", {"details": details, "schedules": schedules})
    else:
        db_id = mb.call("POST", "/database", {"engine": "starrocks", "name": LOOKUP_DB_NAME,
                                              "details": details, "schedules": schedules,
                                              "is_full_sync": True})["id"]
    mb.call("POST", f"/database/{db_id}/sync_schema")
    for _ in range(60):
        tables = [t for t in mb.call("GET", f"/database/{db_id}/metadata")["tables"]
                  if t["name"] == LOOKUP_TABLE]
        if tables and tables[0]["fields"]:
            break
        time.sleep(3)
    else:
        sys.exit(f"Metabase did not pick up {LOOKUP_DB}.{LOOKUP_TABLE}")
    return db_id


def main() -> None:
    load_env(Path(__file__).resolve().parent.parent / ".env")
    base_url = os.environ.get("METABASE_URL", "http://localhost:3000").rstrip("/")
    sr = StarRocks(os.environ.get("STARROCKS_CONTAINER", "starrocks"))
    mb = Metabase(base_url, os.environ["MB_ADMIN_EMAIL"], os.environ["MB_ADMIN_PASSWORD"])

    # 1. Lookup view in StarRocks (recreated so new series are picked up).
    series = device_series.create(sr)
    n = sr.sql(f"SELECT COUNT(*), COUNT(DISTINCT device_id) FROM {LOOKUP_DB}.{LOOKUP_TABLE}")[0]
    print(f"{len({x[0] for x in series})} measurement tables, {len(series)} series; "
          f"lookup view: {n[0]} device/series pairs, {n[1]} devices")

    # 2. Metabase connection to the lookup DB; filter fields get dropdown lists.
    db_id = ensure_metabase_db(mb)
    table = [t for t in mb.call("GET", f"/database/{db_id}/metadata")["tables"]
             if t["name"] == LOOKUP_TABLE][0]
    fields = {fl["name"]: fl for fl in table["fields"]}
    for name in ("device", "metric"):
        mb.call("PUT", f"/field/{fields[name]['id']}",
                {"has_field_values": "list", "semantic_type": "type/Category"})
    mb.call("POST", f"/table/{table['id']}/rescan_values")

    colls = [c for c in mb.call("GET", "/collection")
             if c.get("name") == COLLECTION_NAME and not c.get("archived") and c.get("id") != "root"]
    coll_id = colls[0]["id"] if colls else mb.call("POST", "/collection", {"name": COLLECTION_NAME})["id"]
    cards = {c["name"]: c for c in mb.call("GET", "/card") if not c.get("archived")}

    def upsert(name, body):
        body = {"name": name, "collection_id": coll_id, "type": "question", **body}
        if name in cards:
            return mb.call("PUT", f"/card/{cards[name]['id']}", body)
        return mb.call("POST", "/card", body)

    def native(name, display, select, viz):
        return upsert(name, {
            "display": display, "visualization_settings": viz,
            "dataset_query": {"database": db_id, "type": "native",
                              "native": {"query": series_sql(series, select),
                                         "template-tags": template_tags()}}})

    fref = lambda name: ["field", fields[name]["id"], None]
    overview = upsert("Series of the device", {
        "display": "table", "visualization_settings": {},
        "dataset_query": {"database": db_id, "type": "query", "query": {
            "source-table": table["id"],
            "fields": [fref(c) for c in ("device", "fragment", "series", "unit",
                                         "measurements", "first_time", "last_time")],
            "order-by": [["asc", fref("device")], ["asc", fref("metric")]]}}})
    chart = native("Selected series", "line",
                   # Metabase draws at most 2000 points, so average into buckets sized for
                   # ~1500 per device. `7 [[* 0 + {{days}}]]` is the day count, or 7 if unset.
                   "SELECT FROM_UNIXTIME(FLOOR(UNIX_TIMESTAMP(m.time) / b.seconds) * b.seconds) AS time,\n"
                   "       COALESCE(d.device, m.source) AS device, AVG(m.value) AS value\n"
                   "FROM m LEFT JOIN d ON d.device_id = m.source\n"
                   "CROSS JOIN (SELECT GREATEST(1, CAST(7 [[* 0 + {{days}}]] * 86400 / 1500 AS BIGINT)) AS seconds) b\n"
                   "GROUP BY 1, 2\nORDER BY 1",
                   {"graph.dimensions": ["time", "device"], "graph.metrics": ["value"],
                    "graph.x_axis.title_text": "Time", "graph.y_axis.title_text": "Value"})
    stats = native("Selected series · statistics", "table",
                   "SELECT COALESCE(d.device, m.source) AS device, MAX(m.unit) AS unit,\n"
                   "       COUNT(*) AS measurements, MIN(m.value) AS min, AVG(m.value) AS avg,\n"
                   "       MAX(m.value) AS max, MAX_BY(m.value, m.time) AS latest_value,\n"
                   "       MAX(m.time) AS last_time\n"
                   "FROM m LEFT JOIN d ON d.device_id = m.source\n"
                   "GROUP BY COALESCE(d.device, m.source)\nORDER BY device", {})
    recent = native("Selected series · values", "table",
                    "SELECT m.time, COALESCE(d.device, m.source) AS device, m.value, m.unit\n"
                    "FROM m LEFT JOIN d ON d.device_id = m.source\n"
                    "ORDER BY m.time DESC\nLIMIT 500", {})

    params = [
        {"id": "p_device", "slug": "device", "name": "Device", "type": "string/=",
         "sectionId": "string", "values_query_type": "list"},
        {"id": "p_series", "slug": "series", "name": "Series", "type": "string/=",
         "sectionId": "string", "values_query_type": "list",
         "filteringParameters": ["p_device"]},  # only the selected device's series
        {"id": "p_days", "slug": "days", "name": "Last days", "type": "number/=",
         "sectionId": "number", "default": [7]},
    ]

    def native_mappings(card):
        return [{"parameter_id": p, "card_id": card["id"], "target": ["variable", ["template-tag", tag]]}
                for p, tag in (("p_device", "device"), ("p_series", "series"), ("p_days", "days"))]

    # (card, col, row, width, height, parameter mappings) on Metabase's 24-column grid
    layout = [
        (chart, 0, 0, 24, 9, native_mappings(chart)),
        (stats, 0, 9, 24, 4, native_mappings(stats)),
        (overview, 0, 13, 12, 9, [
            {"parameter_id": "p_device", "card_id": overview["id"], "target": ["dimension", fref("device")]},
            {"parameter_id": "p_series", "card_id": overview["id"], "target": ["dimension", fref("metric")]}]),
        (recent, 12, 13, 12, 9, native_mappings(recent)),
    ]

    dashboards = [d for d in mb.call("GET", "/dashboard")
                  if d["name"] == DASHBOARD_NAME and not d.get("archived")]
    dash = dashboards[0] if dashboards else mb.call("POST", "/dashboard", {"name": DASHBOARD_NAME})
    mb.call("PUT", f"/dashboard/{dash['id']}", {
        "collection_id": coll_id,
        "description": "Pick a device, then one of its series. Only the selected measurement "
                       "table is queried. Device and series lists refresh every 10 minutes.",
        "parameters": params,
        "tabs": [],
        "dashcards": [{"id": -(i + 1), "card_id": c["id"], "col": col, "row": row,
                       "size_x": w, "size_y": h, "parameter_mappings": maps}
                      for i, (c, col, row, w, h, maps) in enumerate(layout)],
    })

    # Cards of earlier versions of this dashboard (single union model, one tab per table).
    keep = {c["id"] for c, *_ in layout}
    archived = 0
    for name, card in cards.items():
        legacy = (name in {"Measurements (all types)", "Measurement count", "Devices reporting",
                           "Series reporting", "Last measurement", "Values over time",
                           "Measurements per fragment", "Statistics per device and series",
                           "Recent measurements"}
                  or re.search(r" · (model|per hour|per device|recent)$", name))
        if legacy and card["id"] not in keep:
            mb.call("PUT", f"/card/{card['id']}", {"archived": True})
            archived += 1
    if archived:
        print(f"archived {archived} cards of earlier dashboard versions")
    print(f"dashboard: {base_url}/dashboard/{dash['id']}")


if __name__ == "__main__":
    main()
